[package]
name = "kairei-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Core engine for Kairei-v2 AgentCulture Framework"
