[package]
name = "kairei-candle"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Candle integration for Kairei-v2 AgentCulture Framework"

[dependencies]
kairei-core = { workspace = true }
candle-core = "0.9"
candle-nn = "0.9"