name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run at 2:00 UTC every Monday
    - cron: '0 2 * * 1'

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo-audit
      uses: actions/cache@v4
      id: audit-cache
      with:
        path: ~/.cargo/bin/cargo-audit
        key: ${{ runner.os }}-cargo-audit
    
    - name: Install cargo-audit
      if: steps.audit-cache.outputs.cache-hit != 'true'
      run: cargo install cargo-audit --force
    
    - name: Run security audit
      run: cargo audit
      
    - name: Check for known vulnerabilities in dependencies
      run: cargo audit --deny warnings